// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class BookAnAppointmentTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void bookAnAppointment() {
    driver.Navigate().GoToUrl("https://katalon-demo-cura.herokuapp.com/");
    driver.Manage().Window.Size = new System.Drawing.Size(975, 1048);
    driver.FindElement(By.Id("btn-make-appointment")).Click();
    driver.FindElement(By.Id("txt-username")).SendKeys("John Doe");
    driver.FindElement(By.Id("txt-password")).SendKeys("ThisIsNotAPassword");
    driver.FindElement(By.Id("btn-login")).Click();
    {
      var dropdown = driver.FindElement(By.Id("combo_facility"));
      dropdown.FindElement(By.XPath("//option[. = 'Hongkong CURA Healthcare Center']")).Click();
    }
    driver.FindElement(By.Id("radio_program_none")).Click();
    driver.FindElement(By.Id("txt_visit_date")).SendKeys("12/12/2023");
    driver.FindElement(By.Id("txt_comment")).SendKeys("sdlhcwlodifhksjdbcwdf");
    driver.FindElement(By.Id("btn-book-appointment")).Click();
    Assert.That(driver.FindElement(By.CssSelector("h2")).Text, Is.EqualTo("Appointment Confirmation"));
    Assert.That(driver.FindElement(By.Id("facility")).Text, Is.EqualTo("Hongkong CURA Healthcare Center"));
    Assert.That(driver.FindElement(By.Id("hospital_readmission")).Text, Is.EqualTo("No"));
    Assert.That(driver.FindElement(By.Id("program")).Text, Is.EqualTo("None"));
    Assert.That(driver.FindElement(By.Id("visit_date")).Text, Is.EqualTo("12/12/2023"));
    Assert.That(driver.FindElement(By.Id("comment")).Text, Is.EqualTo("sdlhcwlodifhksjdbcwdf"));
    driver.FindElement(By.LinkText("Go to Homepage")).Click();
    driver.FindElement(By.Id("menu-toggle")).Click();
    driver.FindElement(By.LinkText("Logout")).Click();
    var elements = driver.FindElements(By.CssSelector("strong"));
    Assert.True(elements.Count > 0);
    driver.Close();
  }
}
