// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class LoginwithInvalidUserandRetryTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void loginwithInvalidUserandRetry() {
    // Test name: Login with Invalid User and Retry
    // Step # | name | target | value
    // 1 | open | / | 
    driver.Navigate().GoToUrl("https://www.saucedemo.com/");
    // 2 | type | id=user-name | user123
    driver.FindElement(By.Id("user-name")).SendKeys("user123");
    // 3 | type | id=password | secret_sauce
    driver.FindElement(By.Id("password")).SendKeys("secret_sauce");
    // 4 | click | id=login-button | 
    driver.FindElement(By.Id("login-button")).Click();
    // 5 | storeText | css=h3 | errorMessage
    vars["errorMessage"] = driver.FindElement(By.CssSelector("h3")).Text;
    // 6 | assertText | css=h3 | Epic sadface: Username and password do not match any user in this service
    Assert.That(driver.FindElement(By.CssSelector("h3")).Text, Is.EqualTo("Epic sadface: Username and password do not match any user in this service"));
    // 7 | if | ${errorMessage}==='Epic sadface: Username and password do not match any user in this service' | 
    if ((Boolean) js.ExecuteScript("return (arguments[0]===\'Epic sadface: Username and password do not match any user in this service\')", vars["errorMessage"])) {
      // 8 | echo | Wrong username | 
      Console.WriteLine("Wrong username");
      // 9 | type | id=user-name | standard_user
      driver.FindElement(By.Id("user-name")).SendKeys("standard_user");
      // 10 | type | css=*[data-test="password"] | secret_sauce
      driver.FindElement(By.CssSelector("*[data-test=\"password\"]")).SendKeys("secret_sauce");
      // 11 | click | id=login-button | 
      driver.FindElement(By.Id("login-button")).Click();
      // 12 | assertText | css=*[data-test="title"] | Products
      Assert.That(driver.FindElement(By.CssSelector("*[data-test=\"title\"]")).Text, Is.EqualTo("Products"));
      // 13 | echo | Login Success | 
      Console.WriteLine("Login Success");
      // 14 | end |  | 
    }
    // 15 | close |  | 
    driver.Close();
  }
}
